name: suma_de_dos_digitos

on:
  push:
    branches:
        - 'test/andres' 
    
jobs:
    suma_de_los_digitos:
        runs-on: ubuntu-latest
        enviroment: 
        outputs:
              suma_result: ${{ steps.sumar.outputs.suma }}
        steps:
            - name: Sumar digitos
              id: sumar
              run: |
                variable1=$${{vars.VARIABLE_UNO }}
                variable2=$${{vars.VARIABLE_DOS }}
                suma=$((variable1 + variable2))
                echo "La suma de $digito1 y $digito2 es: $suma"
                echo "::set-output name=suma::$suma"