name: Operaciones Matemáticas en Paralelo

on:
  push:
    branches:
      - main

jobs:
  operaciones:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operacion: [suma, resta, multiplicacion, division]
    steps:
      - name: Ejecutar ${{ matrix.operacion }}
        run: |
          num1=10
          num2=5
          case "${{ matrix.operacion }}" in
            suma)
              echo $((num1 + num2))
              ;;
            resta)
              echo $((num1 - num2))
              ;;
            multiplicacion)
              echo $((num1 * num2))
              ;;
            division)
              echo $((num1 / num2))
              ;;
          esac