name: suma_de_dos_digitos

on:
  push:
    branches:
        - 'test/andres' 
    
jobs:
    suma_de_los_dos_digitos:
        runs-on: ubuntu-latest
        outputs:
              resultado_de_la_suma: ${{ steps.sumar.outputs.suma }}
        steps:
            - name: Sumar los dos digitos
              id: sumar
              run: |
                variable1=$${{ vars.A }}
                variable2=$${{ vars.B }}
                suma=$((variable1 + variable2))
                echo "La suma de $digito1 y $digito2 es: $suma"
                echo "::set-output name=suma::$suma"
    compara:
        runs-on: ubuntu-latest
        needs: suma_de_los_dos_digitos
        steps:
      - name: Mostrar resultado
        run: |
          suma=${{ needs.suma_de_los_dos_digitos.outputs.resultado_de_la_suma }}
          if [ $suma -gt 10 ]; then
            echo "El resultado de la suma es mayor que 10."
          else
            echo "El resultado de la suma es menor o igual a 10."
          fi