name: suma_de_dos_digitos

on:
  push:
    
env:
    VARIABLE_UNO: 1
    VARIABLE_DOS: 2

jobs:
    suma_de_los_digitos:
        runs-on: ubuntu-latest
        steps:
            - name: Sumar digitos
              resultado= $((vars.VARIABLE_UNO + vars.VARIABLE_UNO))
              run: echo " La suma es $resultado "